PYTHON ?= python3.12
VENV ?= venv
SERVER_HOST ?= 0.0.0.0
SERVER_PORT ?= 8000
WEB_PORT ?= 5173

help:  ## Show help
	@grep -E '^[.a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'

clean: ## Clean autogenerated files
	rm -rf dist
	find . -type f -name "*.DS_Store" -ls -delete
	find . | grep -E "(__pycache__|\.pyc|\.pyo)" | xargs rm -rf
	find . | grep -E ".pytest_cache" | xargs rm -rf
	find . | grep -E ".ipynb_checkpoints" | xargs rm -rf
	rm -f .coverage

clean-logs: ## Clean logs
	rm -rf logs/**

create-package: ## Create wheel and tar gz
	rm -rf dist/
	python setup.py bdist_wheel --plat-name=manylinux1_x86_64
	python setup.py sdist
	python -m twine upload  dist/* --verbose --skip-existing

format: ## Run pre-commit hooks
	pre-commit run -a

sync: ## Merge changes from main branch to your current branch
	git pull
	git pull origin main

test: ## Run not slow tests
	pytest -k "not slow"

test-full: ## Run all tests
	pytest

train-ljspeech: ## Train the model
	python matcha/train.py experiment=ljspeech

train-ljspeech-min: ## Train the model with minimum memory
	python matcha/train.py experiment=ljspeech_min_memory

start_app: ## Start the app
	python matcha/app.py

# --------- server + web app --------- #

install: install-server install-web ## Install server and web app dependencies

install-server: ## Create the venv and install the TTS package and server dependencies
	test -d $(VENV) || $(PYTHON) -m venv $(VENV)
	$(VENV)/bin/python -m pip install --upgrade pip
	$(VENV)/bin/python -m pip install -e .

install-web: ## Install web app dependencies
	cd web && bun install

dev: ## Run server and web app together with hot reload
	$(MAKE) -j2 dev-server dev-web

dev-server: ## Run the TTS server with hot reload
	$(VENV)/bin/python -m uvicorn server.main:app --reload --reload-dir server --reload-dir matcha --host 127.0.0.1 --port $(SERVER_PORT)

dev-web: ## Run the web app dev server (proxies /api to the server)
	cd web && API_PROXY_TARGET=http://127.0.0.1:$(SERVER_PORT) bun run dev --port $(WEB_PORT)

start-server: ## Run the TTS server for production (single worker: the model is loaded per process)
	$(VENV)/bin/python -m uvicorn server.main:app --host $(SERVER_HOST) --port $(SERVER_PORT) --workers 1

build-web: ## Build the web app for production
	cd web && bun run build

.PHONY: install install-server install-web dev dev-server dev-web start-server build-web
